language: python
os: linux
dist: trusty

before_install:
  - sudo apt-get update

jobs:
  include:
    - name: "cpplint"
      script:
        - pip install -U cpplint
        - cpplint --repository=. --recursive --linelength=200 --filter=-build/include,-build/header_guard  ./src
    - name: "cppcheck"
      addons:
        apt:
          packages:
            - cppcheck
      script:
        - cppcheck --error-exitcode=1 --enable=warning,style,performance,portability -DARDUINO_ARCH_ESP32=1 ./src
    - name: "Test"
      script:
        - pip install -U platformio
        - platformio update
        - rm -rf build
        - mkdir build
        - platformio ci --lib="./src" --project-conf="scripts/platformio.ini" --build-dir=build --keep-build-dir tests
        - ./build/.pio/build/catch2/program
    - name: "Memcheck"
      addons:
        apt:
          packages:
            - valgrind
      script:
        - pip install -U platformio
        - platformio update
        - rm -rf build
        - mkdir build
        - platformio ci --lib="./src" --project-conf="scripts/platformio.ini" --build-dir=build --keep-build-dir tests
        - valgrind --leak-check=full ./build/.pio/build/catch2/program
    - name: "Build examples"
      before_install:
        - chmod +x ./scripts/build_examples.sh
      script:
        - ./scripts/build_examples.sh

notifications:
  email:
    on_success: change
    on_failure: change